# Generated by Django 4.2.5 on 2023-09-29 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('clase_id', models.AutoField(primary_key=True, serialize=False)),
                ('matria', models.CharField(max_length=45)),
                ('ano', models.TextField()),
            ],
            options={
                'db_table': 'clase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('departamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('estudiante_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('grado', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'grado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('nivel_id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'nivel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('profesor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('tutor', models.IntegerField()),
            ],
            options={
                'db_table': 'profesor',
                'db_table_comment': '\t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('seccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('seccion', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'seccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('tutoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.TextField()),
            ],
            options={
                'db_table': 'tutoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usario',
            fields=[
                ('usario_id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=45)),
                ('auth_nivel', models.SmallIntegerField()),
                ('auth_id', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'usario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstudianteTieneClase',
            fields=[
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='models.estudiante')),
            ],
            options={
                'db_table': 'estudiante_tiene_clase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotasDeEstudiante',
            fields=[
                ('clase', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='models.clase')),
                ('ano', models.TextField()),
                ('bimestre', models.SmallIntegerField()),
                ('nota', models.CharField(blank=True, max_length=2, null=True)),
                ('comentario', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'notas_de_estudiante',
                'managed': False,
            },
        ),
    ]
