# Generated by Django 4.2.5 on 2023-09-28 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('clase_id', models.AutoField(primary_key=True, serialize=False)),
                ('matria', models.CharField(max_length=45)),
                ('ano', models.PositiveIntegerField(max_length=4)),
            ],
            options={
                'db_table': 'clase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('departamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=15)),
                ('permiso_nivel', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('estudiante_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('grado', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'grado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('nivel_id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'nivel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('notas_id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.CharField(max_length=2)),
                ('comentario', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'notas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('profesor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('tutor', models.IntegerField()),
            ],
            options={
                'db_table': 'profesor',
                'db_table_comment': '\t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('seccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('seccion', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'seccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('tutoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.PositiveIntegerField(max_length=4)),
            ],
            options={
                'db_table': 'tutoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usario',
            fields=[
                ('usario_id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=45)),
                ('auth_nivel', models.SmallIntegerField()),
                ('auth_id', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'usario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstudianteTieneClase',
            fields=[
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='models.estudiante')),
            ],
            options={
                'db_table': 'estudiante_tiene_clase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotasDeEstudiante',
            fields=[
                ('clase', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='models.clase')),
                ('ano', models.PositiveIntegerField(max_length=4)),
            ],
            options={
                'db_table': 'notas_de_estudiante',
                'managed': False,
            },
        ),
    ]
