# Generated by Django 4.2.5 on 2023-10-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('clase_id', models.AutoField(primary_key=True, serialize=False)),
                ('matria', models.CharField(max_length=45)),
                ('ano', models.TextField()),
            ],
            options={
                'db_table': 'clase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('departamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('estudiante_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstudianteTieneClase',
            fields=[
                ('estudiante_tiene_clase_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'estudiante_tiene_clase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('grado', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'grado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('nivel_id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'nivel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotasDeEstudiante',
            fields=[
                ('nota_id', models.AutoField(primary_key=True, serialize=False)),
                ('bimestre', models.SmallIntegerField()),
                ('nota', models.CharField(blank=True, max_length=2, null=True)),
                ('comentario', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'notas_de_estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('profesor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('tutor', models.IntegerField()),
            ],
            options={
                'db_table': 'profesor',
                'db_table_comment': '\t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('seccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('seccion', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'seccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('tutoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.TextField()),
            ],
            options={
                'db_table': 'tutoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usario',
            fields=[
                ('usario_id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=45)),
                ('auth_nivel', models.SmallIntegerField()),
                ('auth_id', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'usario',
                'managed': False,
            },
        ),
    ]
